# -------------------------------------
# RTS Policy Distillation - Config File
# -------------------------------------

# RUN INFO
# --------

env: generals
operation: train  # (train,)

# ENV-SPECIFIC INFO
# ------------------

generals:
  user_id: Byd0qf4R-
  mode: 1v1

# MODEL ARCHITECTURE
# ------------------

dqn_arch:
  inputs:
    observation:
      dtype: float32
      shape: [1884]

  layers:
    - inputs: [observation]
      type: conv
      num_outputs: 16
      kernel_size: 8
      stride: 4
      activation: relu
    - type: conv
      num_outputs: 8
      kernel_size: 4
      stride: 2
      activation: relu
    - type: fc
      size: 128
      activation: relu

  outputs:
    action:
      dtype: float32
      shape: []
      activation: X
