# -------------------------------------
# RTS Policy Distillation - Config File
# -------------------------------------

# RUN INFO
# --------

env: generals_sim
operation: train  # (train,)

# ENV-SPECIFIC INFO
# ------------------

generals_sim:
  map_height: 20
  map_width: 20
  map_player_count: 2

# MODEL ARCHITECTURE
# ------------------

dqn_arch:
  inputs:
    terrain:
      dtype: uint8
      shape: [30, 30, 1]
    ownership:
      dtype: uint8
      shape: [30, 30, 1]
    armies:
      dtype: uint8
      shape: [30, 30, 1]

  layers:
    - inputs: [terrain, ownership, armies]
      type: conv2d
      num_outputs: 32
      kernel_size: 8
      stride: 4
      activation: relu
    - type: conv2d
      num_outputs: 64
      kernel_size: 4
      stride: 2
      activation: relu
    - type: conv2d
      num_outputs: 64
      kernel_size: 3
      stride: 1
      activation: relu
    - type: fc
      num_outputs: 512
      activation: relu

  outputs:
    action:
      dtype: float32
      shape: [5]  # five actions centered around active square
      activation: X
