# -------------------------------------
# RTS Policy Distillation - Config File
# -------------------------------------

# RUN INFO
# --------

env: generals_sim
operation: train  # (train,)

# ENV-SPECIFIC INFO
# ------------------
# (DEP)
generals_sim:
  map_height: 18
  map_width: 18
  map_player_count: 2

# MODEL ARCHITECTURE
# ------------------

dqn_arch:
  inputs:
    terrain:
      dtype: uint8
      shape: [18, 18]
    ownership:
      dtype: uint8
      shape: [18, 18]
    armies:
      dtype: uint8
      shape: [18, 18]

  layers:
    - inputs: [terrain, ownership, armies]
      type: conv2d
      num_outputs: 32
      kernel_size: 8
      stride: 4
      activation: relu
    - type: conv2d
      num_outputs: 64
      kernel_size: 4
      stride: 2
      activation: relu
    - type: conv2d
      num_outputs: 64
      kernel_size: 3
      stride: 1
      activation: relu
    - type: fc
      num_outputs: 512
      activation: relu

  outputs:
    target_x:
      dtype: float32
      shape: [18]
      activation: X
    target_y:
      dtype: float32
      shape: [18]
      activation: X
    action:
      dtype: float32
      shape: [4]  # five actions centered around active square
      activation: X
