# -------------------------------------
# RTS Policy Distillation - Config File
# -------------------------------------

# RUN INFO
# --------

env: generals_sim
operation: train  # (train,)

# ENV-SPECIFIC INFO
# ------------------
generals_sim:
  map_height: 18
  map_width: 18
  map_player_count: 2

# MODEL ARCHITECTURE
# ------------------

dqn_arch:
  inputs:
    mountains:
      dtype: float32 # or uint8?
      shape: [18, 18]
    generals:
      dtype: float32
      shape: [18, 18]
    hidden_terrain:
      dtype: float32
      shape: [18, 18]
    fog:
      dtype: float32
      shape: [18, 18]
    friendly:
      dtype: float32
      shape: [18, 18]
    enemy:
      dtype: float32
      shape: [18, 18]
    cities:
      dtype: float32
      shape: [18, 18]

  layers:
    - inputs: [mountains, generals, hidden_terrain, fog, friendly, enemy, cities]
      type: conv2d
      num_outputs: 32
      kernel_size: 8
      stride: 4
      batch_norm: True
      activation: relu
    - type: conv2d
      num_outputs: 64
      kernel_size: 4
      stride: 2
      batch_norm: True
      activation: relu
    - type: conv2d
      num_outputs: 64
      kernel_size: 3
      stride: 1
      batch_norm: True
      activation: relu
    - type: fc
      num_outputs: 512
      batch_norm: True
      activation: relu

  outputs:
    target_x:
      dtype: float32
      shape: [18]
      activation: X
    target_y:
      dtype: float32
      shape: [18]
      activation: X
    direction:
      dtype: float32
      shape: [4]  # five actions centered around active square
      activation: X
